src/CompanySearchMVC/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CompanySearchMVC.Models;
using CompanySearchMVC.Models.Dto;
using CompanySearchMVC.Services;
using CompanySearchMVC.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CompanySearchMVC.Controllers
{
    public class EventsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private readonly IEventService _eventService;
        private readonly ICategoryService _categoryService;
        public EventsController(ILogger<HomeController> logger, IEventService eventService, ICategoryService categoryService, IMapper mapper)
        {
            _eventService = eventService;
            _categoryService = categoryService;
            _logger = logger;
            _mapper = mapper;
        }

        // GET: ShelfsController
        public async Task<ActionResult> Index()
        {
            var model = await _eventService.GetAllEventsAsync<EventsVm>();
            return View(model);
        }

        // GET: ShelfsController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var model = await _eventService.GetEventByIdAsync<EventDetailsVm>(id);
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var availableCategories = await _categoryService.GetAllCategoriesAsync<CategoriesVm>();
            // ViewBag.AvailableCategories = availableCategories.Categories;
            var model = new CreateEventVm();
            model.AvailableCategories = availableCategories.Categories;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEventVm model)
        {
            if (ModelState.IsValid)
            {
                var availableCategories = await _categoryService.GetAllCategoriesAsync<CategoriesVm>();
                model.EventCategories = availableCategories.Categories
                .Where(c => model.SelectedCategories.Contains(c.Id))
                .ToList();

                var entity = _mapper.Map<CreateEventDto>(model);
                var response = await _eventService.CreateEventAsync<CreateEventDto>(entity);
                // return RedirectToAction(nameof(EventsController.Details), nameof(EventsController).CutController(), new { @Id = entity });
                return RedirectToAction(nameof(EventsController.Index), nameof(EventsController).CutController());

                // return View(model);
            }
            return View(model);
        }

        public IActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(UpdateEventDto model)
        {
            if (ModelState.IsValid)
            {
                var entity = await _eventService.UpdateEventAsync<UpdateEventDto>(model);
                return RedirectToAction(nameof(EventsController.Details), nameof(EventsController).CutController(), new { model.Id });
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            _eventService.DeleteEventAsync<Object>(id);
            return RedirectToAction(nameof(EventsController.Index), nameof(EventsController).CutController());
        }
    }
}

src/CompanySearchMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanySearchMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CompanySearchMVC.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CompanySearchMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!User!.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }

                        @if (User!.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Events"
                                    asp-action="Create">Create Event</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Events"
                                    asp-action="Index">Events</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                    asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CompanySearchMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>